### PR TITLE
Managed YTreeItem first item selection

### PR DESCRIPTION
**Pull request by anaselli**
This partially fixes issue #86 
to have it definitely fixed a patch for libyui-ncurses is also needed, I'll add a further PR

### CODE REVIEW

**Comment by mvidner** [comment]
So, either here, or in #86, we need to describe the problem being fixed, because I still do not understand it.

1. When I write this code (a test case as minimal as possible) and click here and here
2. This should happen
3. But instead this happens

(2 and 3 from the user's perspective, not from the programmer's)

**Comment by mvidner** [comment]
1. Run https://gist.github.com/anaselli/1ca17b78ef619e42c22e#file-test-ytree-selection-cpp in ncurses
2. Item 12345/Item4 should be selected
3. Item 1 (the top one) is selected instead

OK, except the test program is hard to read. Let's strip it down to a minimum.

**Comment by mvidner** [comment]
I have made a reduced version with more friendly item names at https://gist.github.com/mvidner/c4562f7d982f1d4d3c40fb657f0e9d22

**Comment by mvidner** [comment]
What does "managed" in the commit message mean? I think the commit message, and the changelog entry, should read like 

> Fix pre-selecting a YTreeItem when adding it, in ncurses (gh#libyui/libyui#86)

(The ID is an [openSUSE format for referring to tickets](https://en.opensuse.org/openSUSE:Packaging_Patches_guidelines#Current_set_of_abbreviations))

**Comment by anaselli** [comment]
@mvidner sorry so what do you suggest to change the commit message? or just the changelog entry?
btw i have the conflict now as expected :/

**Comment by mvidner** [comment]
The integration tests in
- https://ci.opensuse.org/view/libyui-staging/
- https://build.opensuse.org/project/monitor/devel:libraries:libyui:Staging

look good enough (libyui-gtk is broken in opensuse, we will fix that later) so I want to merge this.

Please make this mergeable, (I've been using https://github.com/mvidner/changelog-chew to automerge changelogs. I think it could be useful for you too).

**Comment by anaselli** [comment]
i could not be able to rebase my change :/

**Comment by mvidner** [comment]
Yay!

**Comment by anaselli** [comment]
:+1:  :dancing_men:

**Pull request merged**
