### PR TITLE
Select preferred UI from environment

### PR DESCRIPTION
**Pull request by besser82**
* Add YSettings::loadedUI option
* Prefer Gtk-UI on Gtk-based desktop enviroments
* Bump SO-name and minor version for API-change

### CODE REVIEW

**Comment by opensusegithubapi** [comment]
Can one of the admins verify this patch?

**Comment by besser82** [comment]
@jreidinger, @mvidner: Any objections on this?

**Comment by jreidinger** [comment]
@besser82 patch wise it looks ok, I am just not sure if we need to bump major of soname. Why minor is not enough?

**Comment by besser82** [comment]
We need to bump major SO-ver, because I added new members to a class.  AFAIK, there is no defined behaviour in C++ about the order of data- and function-members in a class.

For this reason I bumped major SO-ver, to make sure a full rebuild of all UI-components and binary consumers is needed, which would prevent obscure segfaults.

**Comment by jreidinger** [comment]
ok, so feel free to merge it

**Comment by besser82** [comment]
Allrighty, thank you!  =)

**Pull request merged**
