### PR TITLE
Use individual libboost-*-devel packages instead of boost-devel

### PR DESCRIPTION
**Pull request by AdamMajer**

### CODE REVIEW

**Comment by opensusegithubapi** [comment]
Can one of the admins verify this patch?

**Comment by jreidinger** [comment]
@AdamMajer what is basically benefit of this change? reduced build dependencies? how significant change it is?

**Comment by AdamMajer** [comment]
On 03/30/2017 03:13 PM, Josef Reidinger wrote:
> @AdamMajer <https://github.com/AdamMajer> what is basically benefit of
> this change? reduced build dependencies? how significant change it is?

The point is that boost-devel depends on ALL boost libraries and these
libraries are not exactly homogeneous. So boost-devel pulls in quite a
large dependencies set. 99.99% of software only use small fraction of
boost (and most only headers) and since only 1 uses the OpenMPI module,
it was decided that software for next SLE release should not depend on
boost-devel but on individual libraries for these reasons. Also see,

    https://lists.opensuse.org/opensuse-factory/2017-02/msg00024.html

Furthermore, there are more than 2 dozen libraries waiting for inclusion
into boost upstream. If we want to ship boost while not possibly blowing
up the dependency tree even more, then boost-devel has to go away from
BuildRequires.

Yes, this change is important to reduce dependency tree of shipped
products and for maintenance that follows.

All the software in Factory has already been migrated with exception of
3 packages that are maintained on github and seem to not look at OBS
submitrequests ;)

Cheers,
- Adam

**Comment by jreidinger** [comment]
ok, so lets merge

**Pull request merged**
