### PR TITLE
Fix small typo on rest-api examples

### PR DESCRIPTION
**Pull request by ge0r**
Adding a missing ampersand on a rest-api example.

### CODE REVIEW

**Review by shundhammer — APPROVED** [review]
LGTM, thank you!

**Comment by ge0r** [comment]
> LGTM, thank you!

Cheers! Could you also merge please?

**Comment by shundhammer** [comment]
> > LGTM, thank you!
> 
> Cheers! Could you also merge please?

Right now, we have to wait until the hot phase of the SLE-15 SP4 release is done; we'd need a change log entry with a P1 or P2 bug so it's accepted by the release managers (or the first few bots that check any submissions automatically and only due to strict rules, they require a change log entry with a bug number and a version bump).

Let's simply wait a few more weeks, and we can merge it along with other changes. That's a lot less hassle.

**Comment by shundhammer** [comment]
Merging now that SLE-15-SP4 is branched off.

**Comment by shundhammer** [comment]
Thank you for your contribution!

**Pull request merged**
