### PR TITLE
Fixing to build libyui-mga (WITH_MGA option)

### PR DESCRIPTION
**Pull request by anaselli**

### CODE REVIEW

**Review by shundhammer — APPROVED** [review]
LGTM

**Comment by anaselli** [comment]
Thanks, but here i can't merge it, I only can close it...

**Comment by shundhammer** [comment]
Do you want me to merge it?

Is it a permissions problem?

**Comment by shundhammer** [comment]
Merged.

**Comment by anaselli** [comment]
> Merged.

Thanks, yes it is a permission problem. I don't have any rights on this project :+1:

**Pull request merged**
